blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("blogs", views.BlogListView.as_view(), name = "blogs"),
    path("blogs/<slug:slug>", views.BlogDetailView.as_view(), name = "blog-detail"),
]

trustme_backend/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('blog.urls')),
    path('', include('service.urls')),
    path('', include('portfolio.brief.website.urls')),
    path('', include('career.urls')),
    path('', include('portfolio.urls')),
    path('api/', include('api.urls.core')),
    path('api/', include('api.urls.brief')),
    path('api/', include('api.urls.service')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^translation/', include('rosetta.urls'))
    ]

blog/models.py
from django.db import models

# Create your models here.

from django.db import models
from trustme_backend.utils.base_model import BaseModel
from ckeditor.fields import RichTextField
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify


class Blog(BaseModel):
    image = models.ImageField(upload_to='blog/', verbose_name=_('Image'))
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    body = RichTextField(verbose_name=_('Body'))
    author = models.CharField(max_length=255, verbose_name=_('Author'))
    slug = models.SlugField(max_length=255, verbose_name=_('Slug'), unique=True, blank=True)

    class Meta:
        db_table = 'blog'
        verbose_name = _('Blog')
        verbose_name_plural = _('Blogs')

    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)

blog/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import ListView, DetailView
from blog.models import Blog
from django.utils.translation import gettext_lazy as _


class BlogListView(ListView):
    template_name = 'blogs.html'
    model = Blog
    paginate_by = 3
    context_object_name = 'blogs'
    try:
        queryset = Blog.objects.exclude(id=Blog.objects.last().id)
    except:
        queryset = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['last_blog'] = Blog.objects.last()
        context['title'] = _('Blog')
        return context


class BlogDetailView(DetailView):
    template_name = 'blog-detail.html'
    model = Blog
    context_object_name = 'blog'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        context['recommended_blogs'] = Blog.objects.exclude(id=self.object.id)[
            :3]
        return context

blog/templates/blog-detail.html
{% extends 'base.html' %}
{% load static i18n %}
{% block css %}
{% endblock css %}
{% block title %}Trustme{% endblock title %}
{% block content %}

    <main>
        <section class="blog-detail pb-0 pb-lg-5 pt-4 pt-sm-5">
            <div class="g-container">
                <ul class="g-breadcrumb mb-md-4 pb-3">
                    <li class="g-breadcrumb__item">
                        Ana səhifə
                    </li>
                    <li class="g-breadcrumb__item">
                        Blog
                    </li>
                    <li class="g-breadcrumb__item g-breadcrumb__item--active">
                        <a href="">
                            {{blog.title}}
                        </a>
                    </li>
                </ul>

                <div class="blog-detail__img">
                    <img src="{{blog.image.url}}" alt="">
                </div>

                <div class="row g-3">
                    <div class="col-lg-8">
                        <div class="blog-detail__wrapper">
                            <div class="d-flex justify-content-between mb-4">
                                <div class="d-flex flex-column">
                                    <p class="blog-detail__owner">
                                        {{blog.author}}
                                    </p>
                                    <span class="blog-detail__date">
                                        {{blog.created_at|date:"d F, Y"}}
                                    </span>
                                </div>

                                <a href="" class="blog-detail__share">
                                    <img src="{% static 'assets/svg/share.svg' %}" alt="">
                                    <span>Paylaş</span>
                                </a>
                            </div>
                            <h1 class="blog-detail__title mt-sm-4 mt-3">
                                {{blog.title}}
                            </h1>
                            <p class="g-text mt-sm-4 mt-3">
                                {{blog.body|safe}}</p>
                        </div>
                    </div>

                    <div class="col-lg-4 d-none d-lg-block">
                        <p class="blog-detail__helper-title mb-4">
                            Həmçinin bax
                        </p>

                        <div class="blog-detail__recommend">
                            {% for blog in recommended_blogs %}
                            <div class="blog-card">
                                <div class="blog-card__img">
                                    <img src="{{blog.image.url}}" alt="">
                                </div>
                                <div class="blog-card__body">
                                    <a href="{% url 'blog:blog-detail' blog.slug %}" class="blog-card__title">
                                        {{blog.title}}
                                    </a>
                                    <span class="blog-card__date">
                                        {{blog.created_at|date:"d F, Y"}}
                                    </span>
                                    <p class="blog-card__text">
                                        {{blog.body|truncatewords:10|safe|striptags}}
                                    </p>
                                    <a href="{% url 'blog:blog-detail' blog.slug %}" class="blog-card__more">
                                        {% trans 'Daha çox' %}
                                        <img src="{% static 'assets/svg/Vector 106 (1).svg' %}" alt="">
                                    </a>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="blog-detail__recommend-slide pb-3 mt-4 d-lg-none">
                <div class="g-container">
                    <div class="section-title text-center text-xl-start mb-3">
                        <p>BLOQLAR</p>
                        <h2>Marketing bloqları</h2>
                    </div>
                    <div class="swiper blog-detail__slide">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <div class="blog-card">
                                    <div class="blog-card__img">
                                        <img src="{% static 'assets/img/unsplash_WUmb_eBrpjs.png' %}" alt="">
                                    </div>
                                    <div class="blog-card__body">
                                        <a href="" class="blog-card__title">
                                            Instagramın biznesizinizin inkişafında rolu
                                        </a>
                                        <span class="blog-card__date">
                                            12 İyun, 2021
                                        </span>
                                        <p class="blog-card__text">
                                            Reklam və marketinq; Məhsul və xidmətləri, daha geniş kütləyə çatdırmaq və
                                            satış
                                            həcmini artırmaq üçün həyata keçirilən fəaliyyətə verilən addır...
                                        </p>
                                        <a href="" class="blog-card__more">
                                            Daha çox
                                            <img src="{% static 'assets/svg/Vector 106 (1).svg' %}" alt="">
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="blog-card">
                                    <div class="blog-card__img">
                                        <img src="{% static 'assets/img/unsplash_KW3m50XRhjk.png' %}" alt="">
                                    </div>
                                    <div class="blog-card__body">
                                        <a href="" class="blog-card__title">
                                            Rəqəmsal marketinq tarixi
                                        </a>
                                        <span class="blog-card__date">
                                            12 İyun, 2021
                                        </span>
                                        <p class="blog-card__text">
                                            Reklam və marketinq; Məhsul və xidmətləri, daha geniş kütləyə çatdırmaq və
                                            satış
                                            həcmini artırmaq üçün həyata keçirilən fəaliyyətə verilən addır...
                                        </p>
                                        <a href="" class="blog-card__more">
                                            Daha çox
                                            <img src="{% static 'assets/svg/Vector 106 (1).svg' %}" alt="">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-pagination"></div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}
{% block js %}
    <script src="{% static 'js/slides/blogs-recommed.js' %}"></script>
{% endblock js %}

blog/templates/blogs.html
{% extends 'base.html' %}
{% load static i18n %}
{% block css %}
{% endblock css %}
{% block title %}{{title}}{% endblock title %}
{% block content %}

    <main>
        {% if last_blog %}
        <section class="blog-gape pt-4 pt-sm-5">
            <div class="g-container">
                <ul class="g-breadcrumb mb-md-4 pb-3">
                    <li class="g-breadcrumb__item">
                        {% trans 'Ana səhifə' %}
                    </li>
                    <li class="g-breadcrumb__item g-breadcrumb__item--active">
                        <a href="">
                            {% trans 'Bloqlar' %}
                        </a>
                    </li>
                </ul>
                <div class="section-title mb-md-4 pb-3">
                    <h2>{% trans 'Bloq' %}</h2>
                </div>
                <div class="row g-4 d-none d-sm-flex">
                    <div class="col-lg-7">
                        <div class="blog-page__img">
                            <img src="{{last_blog.image.url}}" alt="">
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="blog-page__content">
                            <span class="blog-page__date">
                                {{last_blog.created_at|date:"d F, Y"}}
                            </span>
                            <p class="blog-page__title">
                                {{last_blog.title}}
                            </p>
                            <p class="blog-page__text">
                                {{last_blog.body|truncatewords:50|safe|striptags}}
                            </p>
                            <a href="{% url 'blog:blog-detail' last_blog.slug %}" class="g-btn">
                                {% trans 'Davamını oxu' %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endif %}

        <section class="section-gap">
            <div class="g-container">
                <div class="row g-3">
                    {% for blog in blogs %}
                    <div class="col-sm-6 col-lg-4">
                        <div class="blog-card">
                            <div class="blog-card__img">
                                <img src="{{blog.image.url}}" alt="">
                            </div>
                            <div class="blog-card__body">
                                <a href="" class="blog-card__title">
                                    {{blog.title}}
                                </a>
                                <span class="blog-card__date">
                                    {{blog.created_at|date:"d F, Y"}}
                                </span>
                                <p class="blog-card__text">
                                    {{blog.body|truncatechars:150|safe|striptags}}
                                </p>
                                <a href="{% url 'blog:blog-detail' blog.slug %}" class="blog-card__more">
                                    Daha çox
                                    <img src="{% static 'assets/svg/Vector 106 (1).svg' %}" alt="">
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>



                <ul class="pagination mt-4 mb-4 mb-sm-5 justify-content-center">
                    {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}" class="custom-prev-btn">
                            <svg width="7" height="12" viewBox="0 0 7 12" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M5.29177 1.56665L1.35845 5.27211C0.939395 5.66689 0.939396 6.33308 1.35845 6.72786L5.29177 10.4333"
                                    stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="#" class="custom-prev-btn disabled">
                            <svg width="7" height="12" viewBox="0 0 7 12" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M5.29177 1.56665L1.35845 5.27211C0.939395 5.66689 0.939396 6.33308 1.35845 6.72786L5.29177 10.4333"
                                    stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </a>
                    </li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                    <li class="pagination__item">
                        <a href="#" class="pagination__link pagination__link--active">
                            {{i}}
                        </a>
                    </li>
                    {% else %}
                    <li class="pagination__item">
                        <a href="?page={{ i }}" class="pagination__link">
                            {{i}}
                        </a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}" class="custom-next-btn">
                            <svg width="7" height="12" viewBox="0 0 7 12" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M1.48768 1.56665L5.421 5.27211C5.84005 5.66689 5.84005 6.33308 5.421 6.72786L1.48767 10.4333"
                                    stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="#" class="custom-next-btn disabled">
                            <svg width="7" height="12" viewBox="0 0 7 12" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M1.48768 1.56665L5.421 5.27211C5.84005 5.66689 5.84005 6.33308 5.421 6.72786L1.48767 10.4333"
                                    stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </section>
    </main>

{% endblock content %}


{% block js %}
{% endblock js %}