blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("blogs", views.BlogListView.as_view(), name = "blogs"),
    path("blogs/<slug:slug>", views.BlogDetailView.as_view(), name = "blog-detail"),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path("portfolio/<slug:slug>", views.PortfolioDetailView.as_view(),
         name="portfolio-detail"),
    path("portfolio", views.PortfolioListView.as_view(), name="portfolio"),
]

service/urls.py
from django.urls import path
from . import views

app_name = "service"

urlpatterns = [
    path("digital-audit", views.DigitalAuditView.as_view(), name = "digital-audit"),
    path("packets", views.packets, name = "packets"),
    path("services/<slug:slug>", views.ServiceDetailView.as_view(), name = "service-detail"),
    path("services", views.ServicesListView.as_view(), name = "services"),
]

trustme_backend/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('blog.urls')),
    path('', include('service.urls')),
    path('', include('portfolio.brief.website.urls')),
    path('', include('career.urls')),
    path('', include('portfolio.urls')),
    path('api/', include('api.urls.core')),
    path('api/', include('api.urls.brief')),
    path('api/', include('api.urls.service')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^translation/', include('rosetta.urls'))
    ]

portfolio/brief/website/models.py
from django.db import models

# Create your models here.

from core.models import PHONE_NUMBER_CHOICES
from django.utils.translation import gettext_lazy as _
from trustme_backend.utils.base_model import BaseModel
from multiselectfield import MultiSelectField


ACTIVITY_SPHERE_CHOICES = (
    ('1', 'Activity 1'),
    ('2', 'Activity 2'),
    ('3', 'Activity 3'),
    ('4', 'Activity 4'),
    ('5', 'Activity 5'),
)

PROJECT_PERIOD_CHOICES = (
    ('2', '2 ay'),
    ('3', '3 ay'),
    ('6', '6 ay'),
    ('12', '12 ay'),
)

DESIGN_CHOICES = (
    ('1', 'Design 1'),
    ('2', 'Design 2'),
)

WEBSITE_TYPE_CHOICES = (
    ('1', 'E-commerce'),
    ('2', 'Blog'),
    ('3', 'Portal'),
    ('4', 'Sosial'),
    ('5', 'E-learning'),
)

REQUIREMENTS_CHOICES = (
    ('1', 'IOS'),
    ('2', 'Android'),
    ('3', 'Windows'),
    ('4', 'Mac'),
    ('5', 'Linux'),
)

LANGUAGE_CHOICES = (
    ('az', 'az'),
    ('en', 'en'),
    ('ru', 'ru'),
)


class Brief(BaseModel):
    full_name = models.CharField(max_length=200, verbose_name=_('Full Name'))
    email = models.EmailField(verbose_name=_('Email'))
    phone = models.CharField(max_length=200, verbose_name=_('Phone'))
    phone_prefix = models.CharField(max_length=200, verbose_name=_(
        'Phone Prefix'), choices=PHONE_NUMBER_CHOICES)
    company_name = models.CharField(
        max_length=200, verbose_name=_('Company Name'))
    activity_sphere = models.CharField(max_length=200, verbose_name=_(
        'Activity Sphere'), choices=ACTIVITY_SPHERE_CHOICES)
    website_url = models.URLField(verbose_name=_('Website URL'))
    new_domain = models.CharField(max_length=200, verbose_name=_(
        'New Domain'), blank=True, null=True)
    rival_website = models.TextField(verbose_name=_(
        'Rival Website'), blank=True, null=True)
    liked_website = models.TextField(verbose_name=_(
        'Liked Website'), blank=True, null=True)
    project_period = models.CharField(max_length=200, verbose_name=_(
        'Project Period'), choices=PROJECT_PERIOD_CHOICES)
    design = models.CharField(max_length=200, verbose_name=_(
        'Design'), choices=DESIGN_CHOICES)
    website_type = models.CharField(max_length=200, verbose_name=_(
        'Website Type'), choices=WEBSITE_TYPE_CHOICES)
    requirements = models.CharField(max_length=200, verbose_name=_(
        'Requirements'), choices=REQUIREMENTS_CHOICES)
    language = MultiSelectField(
        choices=LANGUAGE_CHOICES, verbose_name=_('Language'))

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Brief'
        verbose_name_plural = 'Briefs'


class BriefPhoto(BaseModel):
    brief = models.ForeignKey(Brief, on_delete=models.CASCADE, verbose_name=_(
        'Brief'), related_name='brief_photo')
    photo = models.ImageField(verbose_name=_('Photo'))

    def __str__(self):
        return self.brief

    class Meta:
        verbose_name = 'Brief Photo'
        verbose_name_plural = 'Brief Photos'

portfolio/models.py
from django.db import models

# Create your models here.

from trustme_backend.utils.base_model import BaseModel
from ckeditor.fields import RichTextField
from django.utils.translation import gettext_lazy as _

class ProjectStatistic(BaseModel):
    name = models.CharField(max_length=200, verbose_name=_('Name'))
    description = RichTextField(verbose_name=_('Description'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Project Statistic')
        verbose_name_plural = _('Project Statistics')


class ProjectResult(BaseModel):
    title = models.CharField(max_length=200, verbose_name=_('Title'))
    description = RichTextField(verbose_name=_('Description'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Project Result')
        verbose_name_plural = _('Project Results')


class ProjectProcess(BaseModel):
    title = models.CharField(max_length=200, verbose_name=_('Title'))
    period = models.CharField(max_length=200, verbose_name=_('Period'))
    icon = models.ImageField(upload_to='process/', verbose_name=_('Icon'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Project Process')
        verbose_name_plural = _('Project Processes')


class ProjectImage(BaseModel):
    image = models.ImageField(upload_to='projects/', verbose_name=_('Image'))

    def __str__(self):
        return f"{self.image}"

    class Meta:
        verbose_name = _('Project Image')
        verbose_name_plural = _('Project Images')


class ServiceProject(BaseModel):
    url = models.URLField(verbose_name=_('URL'))
    title = models.CharField(max_length=200, verbose_name=_('Title'))
    description = RichTextField(verbose_name=_('Description'))
    aims = RichTextField(verbose_name=_('Aims'))
    cover_image = models.ImageField(
        upload_to='projects/', verbose_name=_('Cover Image'))
    slug = models.SlugField(max_length=200, unique=True,
                            verbose_name=_('Slug'))
    process = models.ManyToManyField(
        ProjectProcess, related_name='project_process', verbose_name=_('Process'), blank=True)
    results = models.ManyToManyField(
        ProjectResult, related_name='project_results', verbose_name=_('Results'), blank=True)
    images = models.ManyToManyField(
        ProjectImage, related_name='project_images', verbose_name=_('Images'), blank=True)
    statistics = models.ManyToManyField(
        ProjectStatistic, related_name='project_statistics', verbose_name=_('Statistics'), blank=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'service_project'
        verbose_name = _('Service Project')
        verbose_name_plural = _('Service Projects')

api/views/brief.py
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions
from api.serializers.brief import BriefSerializer
from portfolio.brief.website.models import Brief


class BriefAPIView(CreateAPIView):
    serializer_class = BriefSerializer
    permission_classes = [permissions.AllowAny]
    model = Brief

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

api/views/service.py
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions
from api.serializers.service import ApplicantSerializer
from service.models import Applicant, Service


class ApplicantAPIView(CreateAPIView):
    serializer_class = ApplicantSerializer
    permission_classes = [permissions.AllowAny]
    model = Applicant

    def create(self, request, *args, **kwargs):
        service_id = request.data.get('service')
        packet = request.data.get('packet')
        vacancy = request.data.get('vacancy')
        project = request.data.get('project')
        if service_id:
            request.data['service'] = Service.objects.get(id=service_id).id
        if packet:
            request.data['packet'] = packet
        if vacancy:
            request.data['vacancy'] = vacancy
        if project:
            request.data['project'] = project
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

portfolio/brief/website/views.py
# Create your views here.

from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _

from portfolio.brief.website.models import ACTIVITY_SPHERE_CHOICES, DESIGN_CHOICES, LANGUAGE_CHOICES, PROJECT_PERIOD_CHOICES, REQUIREMENTS_CHOICES, WEBSITE_TYPE_CHOICES


class BriefView(TemplateView):
    template_name = "brief.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Brief')
        context['brief_choices'] = {
            'activity_sphere_choices': ACTIVITY_SPHERE_CHOICES,
            'website_type_choices': WEBSITE_TYPE_CHOICES,
            'language_choices': LANGUAGE_CHOICES,
            'project_period_choices': PROJECT_PERIOD_CHOICES,
            'design_choices': DESIGN_CHOICES,
            'requirements_choices': REQUIREMENTS_CHOICES,
        }
        return context

portfolio/views.py
from django.shortcuts import render

# Create your views here.

from portfolio.models import ServiceProject
from django.views.generic import ListView, DetailView
from django.utils.translation import gettext_lazy as _
from service.models import Service


class PortfolioDetailView(DetailView):
    model = ServiceProject
    template_name = 'portfolio-detail.html'
    context_object_name = 'portfolio'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        context['recommended_projects'] = ServiceProject.objects.exclude(id=self.object.id)[
            :3]
        return context


class PortfolioListView(ListView):
    template_name = 'portfolio.html'
    context_object_name = 'portfolios'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Portfolio')
        context['services'] = Service.objects.filter(is_visible=True)
        context['portfolio_title'] = Service.objects.filter(slug=self.request.GET.get('service')).first().title if self.request.GET.get(
            'service') else _('Hamısı')
        return context

    def get_queryset(self):
        if self.request.GET.get('service'):
            slug = self.request.GET.get('service')
            service = Service.objects.get(slug=slug)
            return ServiceProject.objects.filter(services_projects=service)
        return ServiceProject.objects.all()

service/views.py
from django.shortcuts import render

from service.models import Service
from django.views.generic import ListView, DetailView, TemplateView
from django.utils.translation import gettext_lazy as _
# Create your views here.


class DigitalAuditView(TemplateView):
    template_name = "digital-audit.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['digital_audit'] = Service.objects.filter(
            slug__icontains='digital-audit').first()
        context['title'] = _('Digital Audit')
        return context


def packets(request):
    return render(request, "packets.html")


class ServicesListView(ListView):
    model = Service
    template_name = 'services.html'
    context_object_name = 'services'


class ServiceDetailView(DetailView):
    model = Service
    template_name = 'service-detail.html'
    context_object_name = 'service'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.filter(is_visible=True)
        return context

service/templates/portfolio-detail.html
{% extends 'base.html' %}
{% load static i18n %}
{% block css %}
{% endblock css %}
{% block title %}{{title}}{% endblock title %}
{% block content %}

    {% include 'partials/apply-modal.html' %}

    <main>
        <section class="project-about pt-sm-5 pt-4">
            <div class="g-container">
                <ul class="g-breadcrumb">
                    <li class="g-breadcrumb__item">
                        Ana səhifə
                    </li>
                    <li class="g-breadcrumb__item">
                        Portfolio
                    </li>
                    <li class="g-breadcrumb__item g-breadcrumb__item--active">
                        <a href="">
                            {{portfolio.title}}
                        </a>
                    </li>
                </ul>
                <div class="section-title mb-4 mt-3">
                    <h2>{{portfolio.title}}</h2>
                </div>
                <div class="row g-3">
                    <div class="col-lg-6">
                        <div class="project-about__content">
                            <h4 class="g-title--purple mb-3">
                                {% trans 'Haqqında' %}
                            </h4>
                            <p class="g-text mb-4">
                                {{portfolio.description|safe}}
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-6 order-lg-2 order-first">
                        <div class="project-about__img">
                            <img src="{{portfolio.cover_image.url}}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="process">
            <img src="{% static 'assets/svg/Line 4.svg' %}" class="process__line d-lg-flex d-none" alt="">

            <div class="g-container">
                <h4 class="g-title--purple mb-3">
                    {% trans 'Proses' %}
                </h4>

                <div class="process__wrapper d-lg-flex d-none">
                    {% for pr in portfolio.process.all %}
                    <div class="process__box">
                        <div class="process__icon">
                            <img src="{{pr.icon.url}}" alt="">
                        </div>
                        <div class="process__right">
                            <p class="process__title">
                                {{pr.title}}
                            </p>
                            <span class="process__subtitle">
                                {{pr.period}}
                            </span>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="swiper process__slide d-lg-none">
                    <div class="swiper-wrapper">
                        {% for pr in portfolio.process.all %}
                        <div class="swiper-slide">
                            <div class="process__box">
                                <div class="process__icon">
                                    <img src="{{pr.icon.url}}" alt="">
                                </div>
                                <div class="process__right">
                                    <p class="process__title">
                                        {{pr.title}}
                                    </p>
                                    <span class="process__subtitle">
                                        {{pr.period}}
                                    </span>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="swiper-pagination"></div>
                </div>
        </section>

        <section class="project-about">
            <div class="g-container">
                <div class="row g-lg-4 g-3">
                    <div class="col-lg-6">
                        <div class="project-about__content">
                            <h4 class="g-title--purple mb-3">
                                {% trans 'Nəticə' %}
                            </h4>
                            <div class="accordion" id="accordionResult">
                                {% for result in portfolio.results.all %}
                                {% if forloop.first %}
                                <div class="accordion-item">
                                    <div class="accordion-header" id="heading{{result.id}}">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#collapse{{result.id}}" aria-expanded="true"
                                            aria-controls="collapse{{result.id}}">
                                            {{result.title}}
                                            <img src="{% static 'assets/svg/acc-icon.svg' %}" alt="">
                                        </button>
                                    </div>
                                    <div id="collapse{{result.id}}" class="accordion-collapse collapse show"
                                        aria-labelledby="heading{{result.id}}">
                                        <div class="accordion-body">
                                            {{result.description|safe}}
                                        </div>
                                    </div>
                                </div>
                                {% else %}
                                <div class="accordion-item">
                                    <div class="accordion-header" id="heading{{result.id}}">
                                        <button class="accordion-button collapsed" type="button"
                                            data-bs-toggle="collapse" data-bs-target="#collapse{{result.id}}"
                                            aria-expanded="false" aria-controls="collapse{{result.id}}">
                                            {{result.title}}
                                            <img src="{% static 'assets/svg/acc-icon.svg' %}" alt="">
                                        </button>
                                    </div>
                                    <div id="collapse{{result.id}}" class="accordion-collapse collapse"
                                        aria-labelledby="heading{{result.id}}">
                                        <div class="accordion-body">
                                           {{result.description|safe}}
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="swiper result-slide">
                            <div class="swiper-wrapper">
                                {% for image in portfolio.images.all %}
                                <div class="swiper-slide">
                                    <div class="result-slide__img">
                                        <img src="{{image.image.url}}" alt="">
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% if portfolio.statistics.count > 0 %}
        <section class="mt-4 mt-md-0">
            <div class="g-container">
                <div class="statistics statistics--four">
                    {% for statistic in portfolio.statistics.all %}
                    <div class="statistics__box">
                        <span class="statistics__numbers">
                            {{statistic.name}}
                        </span>
                        <span class="statistics__text">
                            {{statistic.description|safe}}
                        </span>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        {% endif %}

        <section class="apply-banner section-gap">
            <div class="g-container">
                <div class="apply-banner__wrapper">
                    <p class="apply-banner__title">
                        {% trans 'Xidmətimizdən yararlanmaq istəyirsizmi?' %}
                    </p>
                    <button class="g-btn-fill" data-bs-toggle="modal" data-bs-target="#applyModal">
                        {% trans 'Müraciət et' %}
                    </button>
                </div>
            </div>
        </section>

        {% if recommended_projects.count > 0 %}
        <section class="recommend">
            <div class="g-container">
                <div class="row justify-content-between">
                    <div class="col-xl-2">
                        <div class="d-flex flex-column">
                            <div class="section-title mx-auto mx-xl-0 text-center text-xl-start mb-3 mb-xl-0">
                                <p>{% trans 'PORTFOLİO' %}</p>
                                <h2>{% trans 'Həmçinin bax' %}</h2>
                            </div>

                            <a href="{% url 'portfolio:portfolio' %}" class="g-btn d-none d-xl-flex">
                                {% trans 'Hamısı' %}
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-9">
                        <div class="swiper recommend__slide">
                            <div class="swiper-wrapper">
                                {% for project in recommended_projects %}
                                <div class="swiper-slide">
                                    <a href="{% url 'portfolio:portfolio-detail' project.slug %}" class="recommend__item">
                                        <img src="{{project.image.url}}" alt="">
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endif %}
    </main>
{% endblock content %}

{% block js %}

    <script src="{% static 'js/slides/results-slide.js' %}"></script>
    <script src="{% static 'js/slides/proccess-slide.js' %}"></script>
    <script src="{% static 'js/slides/recommend-slide.js' %}"></script>
    <script src="{% static 'js/apply-form.js' %}"></script>
{% endblock js %}

service/templates/services.html
{% extends 'base.html' %}
{% load static i18n %}
{% block css %}
{% endblock css %}
{% block title %}Trustme{% endblock title %}
{% block content %}

    <main>
        <section class="services pt-4 pt-sm-5">
            <div class="g-container">
                <ul class="g-breadcrumb mb-md-4 pb-3">
                    <li class="g-breadcrumb__item">
                        {% trans 'Ana səhifə' %}
                    </li>
                    <li class="g-breadcrumb__item g-breadcrumb__item--active">
                        <a href="">
                            {% trans 'Xidmətlər' %}
                        </a>
                    </li>
                </ul>

                <div class="section-title mb-3 mb-md-5">
                    <h2>{% trans 'Xidmətlər' %}</h2>
                </div>

                <div class="row g-3 g-md-4">
                    {% for service in services %}
                    <div class="col-lg-4 col-sm-6">
                        <a href="{% url 'service:service-detail' service.slug %}" class="services__box">
                            <img src="{{service.icon.url}}" class="services__icon" alt="">
                            <h3 class="services__title">{{service.title}}</h3>
                            <p class="services__text">
                                {{service.short_description}}
                            </p>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="services__decor">
                <img src="{% static 'assets/svg/decor.svg' %}" alt="">
            </div>
        </section>
    </main>
{% endblock content %}


{% block js %}
{% endblock js %}

service/templates/vacancy.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
{% endblock css %}
{% block title %}Trustme{% endblock title %}
{% block content %}

    <main>
        <section class="blog-detail pt-4 pt-sm-5 mb-4 mb-sm-5">
            <div class="g-container">
                <ul class="g-breadcrumb mb-4">
                    <li class="g-breadcrumb__item">
                        Ana səhifə
                    </li>
                    <li class="g-breadcrumb__item">
                        Kariyera
                    </li>
                    <li class="g-breadcrumb__item g-breadcrumb__item--active">
                        <a href="">
                            Digital Marketing Manager
                        </a>
                    </li>
                </ul>

                <div class="row g-3">
                    <div class="col-lg-8">
                        <div class="blog-detail__wrapper">
                            <span class="chip mb-2">
                                Təcrübə
                            </span>
                            <h1 class="blog-detail__title mb-3 mb-sm-5">
                                Digital Marketing Manager
                            </h1>
                            <h2 class="blog-detail__subtitle mb-3">
                                Haqqında
                            </h2>
                            <p class="blog-detail__text mb-3 mb-sm-5">
                                Komandamıza qoşulmaq və məqsədlərimizə nail olmaq üçün kreativ ideyalar təqdim etmək
                                üçün həvəsli rəqəmsal marketinq üzrə təcrübəçi axtarırıq.
                            </p>
                            <h2 class="blog-detail__subtitle mb-3">
                                Məsuliyyətlər
                            </h2>
                            <p class="blog-detail__text mb-3 mb-sm-5">
                                Təcrübəçi olaraq, kampaniyaların bütün mərhələlərində komandalarımızla əməkdaşlıq
                                edəcəksiniz.
                            </p>
                            <h2 class="blog-detail__subtitle mb-3">
                                Məsuliyyətlər
                            </h2>
                            <ul class="">
                                <li>
                                    Sürətli templi mühitdə çoxlu tapşırıqlar yerinə yetirmək bacarığı
                                </li>
                                <li>
                                    Gündə ən azı 3 saat hazır olun
                                </li>
                                <li>
                                    Təşəbbüskar olmaq bacarığı
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="apply-box">
                            <p class="blog-detail__subtitle mb-4 pb-1">
                                Müraciət et
                            </p>
                            <form action="">
                                <div class="g-input-group">
                                    <label for="name">Ad və soyad <span>*</span></label>
                                    <input id="name" type="text" placeholder="Ad və soyadınızı daxil edin">
                                </div>
                                <div class="g-input-group">
                                    <label for="message">Mesaj <span>*</span></label>
                                    <textarea id="message" name="" placeholder="Mesajınızı yazın" cols="30"
                                        rows="10"></textarea>
                                </div>
                                <div class="g-input-group">
                                    <label for="message">CV <span>*</span></label>
                                    <div class="file-drop-area">
                                        <span class="file-msg">
                                            Sürüşdürün və ya <b>yükləyin</b>
                                        </span>
                                        <input class="file-input" type="file" multiple>
                                    </div>
                                </div>

                                <button type="submit" class="g-btn-fill w-100">Göndər</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    
{% endblock content %}

{% block js %}
    <script src="{% static 'js/uplod.js' %}"></script>

{% endblock js %}