blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("blogs", views.BlogListView.as_view(), name = "blogs"),
    path("blogs/<slug:slug>", views.BlogDetailView.as_view(), name = "blog-detail"),
]

career/urls.py
from django.urls import path
from . import views

app_name = "career"

urlpatterns = [
    path("careers", views.VacancyListView.as_view(), name = "careers"),
    path("careers/<slug:slug>", views.VacancyDetailView.as_view(), name = "career-detail"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name = "home"),
    path("faq", views.FAQView.as_view(), name = "faq"),
    path("about-us", views.AboutUsView.as_view(), name = "about_us"),
    path("contact", views.ContactView.as_view(), name = "contact"),
    path('set_language/', views.set_language, name="set_language")
]

trustme_backend/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('blog.urls')),
    path('', include('service.urls')),
    path('', include('portfolio.brief.website.urls')),
    path('', include('career.urls')),
    path('', include('portfolio.urls')),
    path('api/', include('api.urls.core')),
    path('api/', include('api.urls.brief')),
    path('api/', include('api.urls.service')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^translation/', include('rosetta.urls'))
    ]

career/models.py
from django.db import models

# Create your models here.

from trustme_backend.utils.base_model import BaseModel
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

VACANCY_TYPE_CHOICES = (
    (_('Full time'), _('Full time')),
    (_('Part time'), _('Part time')),
    (_('Internship'), _('Internship')),
)


class Vacancy(BaseModel):
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    type = models.CharField(verbose_name=_(
        'Type'), choices=VACANCY_TYPE_CHOICES, default='full_time', max_length=255)
    short_description = models.TextField(verbose_name=_('Short Description'))
    full_description = RichTextField(verbose_name=_('Full Description'))
    slug = models.SlugField(
        max_length=255, verbose_name=_('Slug'), unique=True)

    class Meta:
        db_table = 'vacancy'
        verbose_name = _('Vacancy')
        verbose_name_plural = _('Vacancies')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Vacancy, self).save(*args, **kwargs)

core/models.py
from django.db import models

# Create your models here.

from trustme_backend.utils.base_model import BaseModel
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField

PHONE_NUMBER_CHOICES = (
    ('+994', '+994'),
    ('+7', '+7'),
    ('+1', '+1'),
    ('+90', '+90'),
)


STAR_CHOICES = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
)


class AboutUs(BaseModel):
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    description = RichTextField(verbose_name=_('Description'))
    is_active = models.BooleanField(default=True, verbose_name=_('Is active'))

    class Meta:
        db_table = 'about_us'
        verbose_name = _('About Us')
        verbose_name_plural = _('About Us')

    def __str__(self):
        return self.title


class AboutUsSlogan(BaseModel):
    about_us = models.ForeignKey(
        AboutUs, on_delete=models.CASCADE, verbose_name=_('About us'), related_name='about_us_slogan')
    slogan = models.TextField(verbose_name=_('Slogan'))
    slogan_author = models.CharField(
        max_length=255, verbose_name=_('Slogan author'))
        
    class Meta:
        db_table = 'about_us_slogan'
        verbose_name = _('About Us Slogan')
        verbose_name_plural = _('About Us Slogan')

    def __str__(self):
        return self.slogan


class AboutUsStatistic(BaseModel):
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'))
    about_us = models.ForeignKey(
        AboutUs, on_delete=models.CASCADE, verbose_name=_('About Us'), related_name='about_us_statistic')

    class Meta:
        db_table = 'about_us_statistic'
        verbose_name = _('About Us Statistic')
        verbose_name_plural = _('About Us Statistic')

    def __str__(self):
        return self.title


class AboutUsInfo(BaseModel):
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'))
    icon = models.ImageField(
        upload_to='about_us_info/', verbose_name=_('Icon'))
    mobile_icon = models.ImageField(
        upload_to='about_us_info/', verbose_name=_('Mobile icon'))
    about_us = models.ForeignKey(
        AboutUs, on_delete=models.CASCADE, verbose_name=_('About Us'), related_name='about_us_info')

    class Meta:
        db_table = 'about_us_info'
        verbose_name = _('About Us Info')
        verbose_name_plural = _('About Us Info')

    def __str__(self):
        return self.title


class AboutUsTeam(BaseModel):
    full_name = models.CharField(max_length=255, verbose_name=_('Full name'))
    position = models.CharField(max_length=255, verbose_name=_('Position'))
    description = models.TextField(verbose_name=_('Description'))
    image = models.ImageField(
        upload_to='about_us_team/', verbose_name=_('Image'))
    about_us = models.ForeignKey(
        AboutUs, on_delete=models.CASCADE, verbose_name=_('About Us'), related_name='about_us_team')

    class Meta:
        db_table = 'about_us_team'
        verbose_name = _('About Us Team')
        verbose_name_plural = _('About Us Team')

    def __str__(self):
        return self.full_name


class Testimonial(BaseModel):
    full_name = models.CharField(max_length=255, verbose_name=_('Full name'))
    company_name = models.CharField(
        max_length=255, verbose_name=_('Company name'))
    position = models.CharField(max_length=255, verbose_name=_('Position'))
    comment = models.TextField(verbose_name=_('Comment'))
    star = models.IntegerField(verbose_name=_(
        'Star'), choices=STAR_CHOICES, default=1)
    is_active = models.BooleanField(default=False, verbose_name=_('Is active'))

    class Meta:
        db_table = 'testimonial'
        verbose_name = _('Testimonial')
        verbose_name_plural = _('Testimonials')

    def __str__(self):
        return self.full_name


class ContactInfo(BaseModel):
    email = models.EmailField(verbose_name=_('Email'))
    address = models.TextField(verbose_name=_('Address'))
    is_active = models.BooleanField(default=True, verbose_name=_('Is active'))

    class Meta:
        db_table = 'contact_info'
        verbose_name = _('Contact Info')
        verbose_name_plural = _('Contact Info')

    def __str__(self):
        return self.email


class ContactPhone(BaseModel):
    phone_number = models.CharField(
        max_length=255, verbose_name=_('Phone number'))
    contact_info = models.ForeignKey(
        ContactInfo, on_delete=models.CASCADE, verbose_name=_('Contact info'), related_name='contact_phone')

    class Meta:
        db_table = 'contact_phone'
        verbose_name = _('Contact Phone')
        verbose_name_plural = _('Contact Phone')

    def __str__(self):
        return self.phone_number


class SocialLink(BaseModel):
    link = models.URLField(verbose_name=_('Link'))
    icon = models.ImageField(
        upload_to='social_link/', verbose_name=_('Icon'))
    is_active = models.BooleanField(default=True, verbose_name=_('Is active'))
    contact_info = models.ForeignKey(
        ContactInfo, on_delete=models.CASCADE, verbose_name=_('Contact info'), related_name='social_link')

    class Meta:
        db_table = 'social_link'
        verbose_name = _('Social Link')
        verbose_name_plural = _('Social Link')

    def __str__(self):
        return f"{self.link}"

career/forms.py
from django import forms
from django.forms import ModelForm
from service.models import Applicant
from django.forms.widgets import Textarea


class VacancyForm(ModelForm):
    class Meta:
        model = Applicant
        fields = ('full_name', 'message', 'cv', 'vacancy')

        widgets = {
            'full_name': forms.TextInput(attrs={'placeholder': 'Ad və soyadınızı daxil edin'}),
            'message': forms.Textarea(attrs={'placeholder': 'Mesajınızı yazın'}),
            'cv': forms.FileInput(attrs={'class': 'file-input'}),
            'vacancy': forms.HiddenInput(),
        }

    def clean_cv(self):
        cv = self.cleaned_data['cv']
        if not cv:
            raise forms.ValidationError('CV yüklənməlidir')
        return cv

    def clean_full_name(self):
        full_name = self.cleaned_data['full_name']
        if not full_name or len(full_name.split(' ')) < 2:
            raise forms.ValidationError('Ad və soyadınızı daxil edin')
        return full_name

api/views/core.py
from rest_framework.generics import CreateAPIView
from rest_framework import permissions
from api.serializers.core import TestimonialSerializer
from core.models import Testimonial


class TestimonialAPIView(CreateAPIView):
    serializer_class = TestimonialSerializer
    permission_classes = [permissions.AllowAny]
    model = Testimonial

career/views.py
# Create your views here.
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, CreateView
from django.utils.translation import gettext_lazy as _
from career.forms import VacancyForm
from career.models import Vacancy
from service.models import Applicant


class VacancyListView(ListView):
    model = Vacancy
    template_name = 'careers.html'
    context_object_name = 'vacancies'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Careers')
        return context


class VacancyDetailView(DetailView, CreateView):
    form_class = VacancyForm
    template_name = 'vacancy.html'
    context_object_name = 'vacancy'
    model = Vacancy

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Vacancy.objects.get(slug=self.kwargs['slug']).title
        return context

    def post(self, request, *args, **kwargs):
        self.object = Vacancy.objects.get(slug=self.kwargs['slug'])
        form = self.get_form()
        if form.is_valid():
            # form.cleaned_data['vacancy'] = self.object
            # applicant = Applicant.objects.create(**form.cleaned_data)
            applicant = Applicant.objects.create(
                full_name=form.cleaned_data['full_name'],
                vacancy=self.object,
                message=form.cleaned_data['message'],
                cv=form.cleaned_data['cv'],
            )
            applicant.save()
            messages.success(request, _('Your application has been sent successfully.'))
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return '/careers/{}'.format(self.kwargs['slug'])

core/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
from core.models import AboutUs, Testimonial
from blog.models import Blog
from django.db.models import Count
from django.utils.translation import gettext_lazy as _, activate
from service.models import Service, ServiceCategory, ServiceProject

# Create your views here.


class HomeView(View):
    def get(self, request):
        context = {
            'title': _('Home'),
            'services': Service.objects.filter(is_visible=True),
            'blogs': Blog.objects.all(),
            'about_us': AboutUs.objects.filter(is_active=True).last(),
            'services_categories': Service.objects.annotate(Count('projects')).order_by('-projects__count')[:3],
            'services_categories_for_mobile': Service.objects.annotate(Count('projects')).order_by('-projects__count'),
            'projects': ServiceProject.objects.all()[:5],
            'testimonials': Testimonial.objects.filter(is_active=True).order_by('star'),
        }
        return render(request, "home.html", context=context)


class FAQView(TemplateView):
    template_name = 'faq.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('FAQ')
        context['services'] = Service.objects.filter(is_visible=True)
        context['categories'] = self.get_queryset()
        return context

    def get_queryset(self):
        if self.request.GET.get('service'):
            return Service.objects.filter(is_visible=True, slug=self.request.GET.get('service')).first().categories.all()
        return ServiceCategory.objects.all()


class AboutUsView(TemplateView):
    template_name = "about-us.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('About Us')
        context['about_us'] = AboutUs.objects.filter(is_active=True).last()
        return context


class ContactView(TemplateView):
    template_name = "contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Contact')
        return context


def set_language(request):
    if request.GET.get('lang'):
        activate(request.GET.get('lang'))
        response = HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        response.set_cookie('django_language', request.GET['lang'])
        return response

core/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/css/bootstrap/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <link rel="stylesheet" href="{% static 'styles/css/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/main.min.css' %}">

    {% block css %}
    {% endblock css %}

    <title>{% block title %}{% endblock title %}</title>

</head>

<body>

{% include 'partials/navbar.html' %}


{% block content %}
{% endblock content %}


{% include 'partials/footer.html' %}


<script src="{% static 'js/min/jquery.min.js' %}"></script>
<script src="{% static 'js/min/bootstrap.bundle.min.js' %}"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script src="{% static 'js/min/select2.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

{% block js %}
{% endblock js %}


</body>

</html>

core/templates/careers.html
{% extends 'base.html' %}
{% load static i18n %}
{% block css %}
{% endblock css %}
{% block title %}{{title}}{% endblock title %}
{% block content %}

    <main>
        <section class="services pt-sm-5 pt-4">
            <div class="g-container">
                <ul class="g-breadcrumb  mb-3">
                    <li class="g-breadcrumb__item">
                        Ana səhifə
                    </li>
                    <li class="g-breadcrumb__item g-breadcrumb__item--active">
                        <a href="">
                            Kariyera
                        </a>
                    </li>
                </ul>

                <div class="section-title mb-3 mb-md-5">
                    <h2>Komandamıza qoşul</h2>
                </div>

                <div class="row g-4">
                    {% for vacancy in vacancies %}
                    <div class="col-sm-6 col-lg-4">
                        <a href="{% url 'core:career-detail' vacancy.slug %}" class="services__box services__box--career">
                            <span class="chip mb-3">
                                {{vacancy.type}}
                            </span>
                            <h3 class="services__title">{{vacancy.title}}</h3>
                            <p class="services__text services__text--career">
                                {{vacancy.short_description}}
                            </p>
                        </a>
                    </div>
                    {% endfor %}
                </div>

                <ul class="pagination mt-4 mb-4 mb-sm-5 justify-content-center">
                    {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}" class="custom-prev-btn">
                            <svg width="7" height="12" viewBox="0 0 7 12" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M5.29177 1.56665L1.35845 5.27211C0.939395 5.66689 0.939396 6.33308 1.35845 6.72786L5.29177 10.4333"
                                    stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="#" class="custom-prev-btn disabled">
                            <svg width="7" height="12" viewBox="0 0 7 12" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M5.29177 1.56665L1.35845 5.27211C0.939395 5.66689 0.939396 6.33308 1.35845 6.72786L5.29177 10.4333"
                                    stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </a>
                    </li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                    <li class="pagination__item">
                        <a href="#" class="pagination__link pagination__link--active">
                            {{i}}
                        </a>
                    </li>
                    {% else %}
                    <li class="pagination__item">
                        <a href="?page={{ i }}" class="pagination__link">
                            {{i}}
                        </a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}" class="custom-next-btn">
                            <svg width="7" height="12" viewBox="0 0 7 12" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M1.48768 1.56665L5.421 5.27211C5.84005 5.66689 5.84005 6.33308 5.421 6.72786L1.48767 10.4333"
                                    stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="#" class="custom-next-btn disabled">
                            <svg width="7" height="12" viewBox="0 0 7 12" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M1.48768 1.56665L5.421 5.27211C5.84005 5.66689 5.84005 6.33308 5.421 6.72786L1.48767 10.4333"
                                    stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                            </svg>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div class="services__decor">
                <img src="{% static 'assets/svg/decor.svg' %}" alt="">
            </div>
        </section>
    </main>
{% endblock content %}
{% block js %}
{% endblock js %}

core/templates/faq.html
{% extends 'base.html' %}
{% load static i18n %}
{% block css %}
{% endblock css %}
{% block title %}{{title}}{% endblock title %}

{% block content %}

    <main>
        <section class="faq mb-sm-5 mb-3 pt-sm-5 pt-4">
            <div class="g-container">
                <ul class="g-breadcrumb mb-md-4 pb-3">
                    <li class="g-breadcrumb__item">
                        Ana səhifə
                    </li>
                    <li class="g-breadcrumb__item g-breadcrumb__item--active">
                        <a href="">
                            {% trans 'FAQ' %}
                        </a>
                    </li>
                </ul>

                <div class="faq__wrapper">
                    <ul class="dashboard">
                        <li class="dashboard__item">
                            <a href="{% url 'core:faq' %}" class="dashboard__link {% if not request.GET.service %}  dashboard__link--active {% endif %}">
                                <img src="{% static 'assets/svg/copy1.svg' %}" alt=""> Hamısı
                            </a>
                        </li>
                        {% for service in services %}
                        <li class="dashboard__item">
                            <a href="?service={{ service.slug }}" class="dashboard__link {% if request.GET.service == service.slug %}dashboard__link--active{% endif %}">
                                <img src="{{service.icon.url}}" alt="">{{service.title}}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>

                    <ul class="categories-tab">
                        <li class="categories-tab__item {% if not request.GET.service %}  categories-tab__item--active {% endif %}">
                            <a href="{% url 'core:faq' %}">
                                {% trans 'Hamısı' %}
                            </a>
                        </li>
                        {% for service in services %}
                        <li class="categories-tab__item {% if request.GET.service == service.slug %}categories-tab__item--active{% endif %}">
                            <a href="?service={{ service.slug }}">
                                {{service.title}}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="w-100 ps-lg-4 ms-lg-2">
                        <div class="accordion" id="accordionCategory">
                            {% for category in categories %}
                            <div class="accordion-item">
                                <div class="accordion-header" id="heading{{category.id}}">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapse{{category.id}}" aria-expanded="{% if forloop.first %}true{% else %}false{% endif %}" aria-controls="collapse{{category.id}}">
                                        {{category.question}}
                                        <img src="{% static 'assets/svg/acc-icon.svg' %}" alt="">
                                    </button>
                                </div>
                                <div id="collapse{{category.id}}" class="accordion-collapse collapse {% if forloop.first %}show{% endif %}"
                                    aria-labelledby="heading{{category.id}}" >
                                    <div class="accordion-body">
                                        {{category.answer|safe}}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock content %}

{% block js %}
{% endblock %}

core/templates/vacancy.html
{% extends 'base.html' %}
{% load static i18n %}
{% block css %}
{% endblock css %}
{% block title %}{{title}}{% endblock title %}
{% block content %}

    <main>
        <section class="blog-detail pt-4 pt-sm-5 mb-4 mb-sm-5">
            <div class="g-container">
                <ul class="g-breadcrumb mb-4">
                    <li class="g-breadcrumb__item">
                        Ana səhifə
                    </li>
                    <li class="g-breadcrumb__item">
                        Kariyera
                    </li>
                    <li class="g-breadcrumb__item g-breadcrumb__item--active">
                        <a href="">
                            Digital Marketing Manager
                        </a>
                    </li>
                </ul>

                <div class="row g-3">
                    <div class="col-lg-8">
                        <div class="blog-detail__wrapper">
                            <span class="chip mb-2">
                                {{vacancy.type}}
                            </span>
                            <h1 class="blog-detail__title mb-3 mb-sm-5">
                                {{vacancy.title}}
                            </h1>
                            <h2 class="blog-detail__subtitle mb-3">
                                {% trans 'Haqqında' %}
                            </h2>
                            <p class="blog-detail__text mb-3 mb-sm-5">
                                {{vacancy.short_description}}
                            </p>
                            <p class="blog-detail__text mb-3 mb-sm-5">
                                {{vacancy.full_description|safe|striptags}}
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="apply-box">
                            <p class="blog-detail__subtitle mb-4 pb-1">
                                Müraciət et
                            </p>
                            <form action="" method="post" id="applicantform" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="g-input-group">
                                    <label for="full_name">Ad və soyad <span>*</span></label>
                                    <input id="full_name" type="text" placeholder="Ad və soyadınızı daxil edin">
                                </div>
                                <div class="g-input-group">
                                    <label for="message">Mesaj <span>*</span></label>
                                    <textarea id="message" name="" placeholder="Mesajınızı yazın" cols="30"
                                        rows="10"></textarea>
                                </div>
                                <div class="g-input-group">
                                    <label for="message">CV <span>*</span></label>
                                    <div class="file-drop-area">
                                        <span class="file-msg">
                                            Sürüşdürün və ya <b>yükləyin</b>
                                        </span>
                                        <input id="cv" class="file-input" type="file" multiple>
                                    </div>
                                </div>

                                <button id="applicant-submit" type="submit" class="g-btn-fill w-100">Göndər</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    
{% endblock content %}

{% block js %}
    <script src="{% static 'js/uplod.js' %}"></script>
    <script>
        applicantform = document.getElementById('applicantform');
        const ApplicantLogic = {
            applicantManager(data) {
                fetch('/api/applicant', {
                    method: 'POST',
                    credentials: 'include',
                    headers: {
                        "X-CSRFToken": applicantform.csrfmiddlewaretoken.value,
                        'Content-Type': 'application/json',
                        'Content-Disposition': 'attachment; filename="cv.pdf"'
                    },
                    body: JSON.stringify({
                        'full_name': data.full_name,
                        'cv': data.cv,
                        'message': data.message,
                        'vacancy': data.vacancy
                    })
                })
                    .then(response => response.json())
                    .then(data => {
                        console.log(data);
                    });
            }
        }
        applicant_submit = document.getElementById('applicant-submit');
        applicant_submit.addEventListener('click', function (e) {
            e.preventDefault();
            full_name = document.getElementById('full_name').value;
            cv = document.getElementById('cv').value;
            vacancy = window.location.pathname.split('/')[2];
            message = document.getElementById('message').value;
            data = {
                'full_name': full_name,
                'cv': cv,
                'message': message,
                'vacancy': vacancy
            }
            ApplicantLogic.applicantManager(data);
        });
    </script>
{% endblock js %}