blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("blogs", views.BlogListView.as_view(), name = "blogs"),
    path("blogs/<slug:slug>", views.BlogDetailView.as_view(), name = "blog-detail"),
]

career/urls.py
from django.urls import path
from . import views

app_name = "career"

urlpatterns = [
    path("careers", views.VacancyListView.as_view(), name = "careers"),
    path("careers/<slug:slug>", views.VacancyDetailView.as_view(), name = "career-detail"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name = "home"),
    path("faq", views.FAQView.as_view(), name = "faq"),
    path("about-us", views.AboutUsView.as_view(), name = "about_us"),
    path("contact", views.ContactView.as_view(), name = "contact"),
    path('set_language/', views.set_language, name="set_language")
]

portfolio/brief/website/urls.py
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path("brief", views.BriefView.as_view(), name="brief"),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path("portfolio/<slug:slug>", views.PortfolioDetailView.as_view(),
         name="portfolio-detail"),
    path("portfolio", views.PortfolioListView.as_view(), name="portfolio"),
]

service/urls.py
from django.urls import path
from . import views

app_name = "service"

urlpatterns = [
    path("digital-audit", views.DigitalAuditView.as_view(), name = "digital-audit"),
    path("packets", views.packets, name = "packets"),
    path("services/<slug:slug>", views.ServiceDetailView.as_view(), name = "service-detail"),
    path("services", views.ServicesListView.as_view(), name = "services"),
]

trustme_backend/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('blog.urls')),
    path('', include('service.urls')),
    path('', include('portfolio.brief.website.urls')),
    path('', include('career.urls')),
    path('', include('portfolio.urls')),
    path('api/', include('api.urls.core')),
    path('api/', include('api.urls.brief')),
    path('api/', include('api.urls.service')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^translation/', include('rosetta.urls'))
    ]

core/models.py
from django.db import models

# Create your models here.

from trustme_backend.utils.base_model import BaseModel
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField

PHONE_NUMBER_CHOICES = (
    ('+994', '+994'),
    ('+7', '+7'),
    ('+1', '+1'),
    ('+90', '+90'),
)


STAR_CHOICES = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
)


class AboutUs(BaseModel):
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    description = RichTextField(verbose_name=_('Description'))
    is_active = models.BooleanField(default=True, verbose_name=_('Is active'))

    class Meta:
        db_table = 'about_us'
        verbose_name = _('About Us')
        verbose_name_plural = _('About Us')

    def __str__(self):
        return self.title


class AboutUsSlogan(BaseModel):
    about_us = models.ForeignKey(
        AboutUs, on_delete=models.CASCADE, verbose_name=_('About us'), related_name='about_us_slogan')
    slogan = models.TextField(verbose_name=_('Slogan'))
    slogan_author = models.CharField(
        max_length=255, verbose_name=_('Slogan author'))
        
    class Meta:
        db_table = 'about_us_slogan'
        verbose_name = _('About Us Slogan')
        verbose_name_plural = _('About Us Slogan')

    def __str__(self):
        return self.slogan


class AboutUsStatistic(BaseModel):
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'))
    about_us = models.ForeignKey(
        AboutUs, on_delete=models.CASCADE, verbose_name=_('About Us'), related_name='about_us_statistic')

    class Meta:
        db_table = 'about_us_statistic'
        verbose_name = _('About Us Statistic')
        verbose_name_plural = _('About Us Statistic')

    def __str__(self):
        return self.title


class AboutUsInfo(BaseModel):
    title = models.CharField(max_length=255, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'))
    icon = models.ImageField(
        upload_to='about_us_info/', verbose_name=_('Icon'))
    mobile_icon = models.ImageField(
        upload_to='about_us_info/', verbose_name=_('Mobile icon'))
    about_us = models.ForeignKey(
        AboutUs, on_delete=models.CASCADE, verbose_name=_('About Us'), related_name='about_us_info')

    class Meta:
        db_table = 'about_us_info'
        verbose_name = _('About Us Info')
        verbose_name_plural = _('About Us Info')

    def __str__(self):
        return self.title


class AboutUsTeam(BaseModel):
    full_name = models.CharField(max_length=255, verbose_name=_('Full name'))
    position = models.CharField(max_length=255, verbose_name=_('Position'))
    description = models.TextField(verbose_name=_('Description'))
    image = models.ImageField(
        upload_to='about_us_team/', verbose_name=_('Image'))
    about_us = models.ForeignKey(
        AboutUs, on_delete=models.CASCADE, verbose_name=_('About Us'), related_name='about_us_team')

    class Meta:
        db_table = 'about_us_team'
        verbose_name = _('About Us Team')
        verbose_name_plural = _('About Us Team')

    def __str__(self):
        return self.full_name


class Testimonial(BaseModel):
    full_name = models.CharField(max_length=255, verbose_name=_('Full name'))
    company_name = models.CharField(
        max_length=255, verbose_name=_('Company name'))
    position = models.CharField(max_length=255, verbose_name=_('Position'))
    comment = models.TextField(verbose_name=_('Comment'))
    star = models.IntegerField(verbose_name=_(
        'Star'), choices=STAR_CHOICES, default=1)
    is_active = models.BooleanField(default=False, verbose_name=_('Is active'))

    class Meta:
        db_table = 'testimonial'
        verbose_name = _('Testimonial')
        verbose_name_plural = _('Testimonials')

    def __str__(self):
        return self.full_name


class ContactInfo(BaseModel):
    email = models.EmailField(verbose_name=_('Email'))
    address = models.TextField(verbose_name=_('Address'))
    is_active = models.BooleanField(default=True, verbose_name=_('Is active'))

    class Meta:
        db_table = 'contact_info'
        verbose_name = _('Contact Info')
        verbose_name_plural = _('Contact Info')

    def __str__(self):
        return self.email


class ContactPhone(BaseModel):
    phone_number = models.CharField(
        max_length=255, verbose_name=_('Phone number'))
    contact_info = models.ForeignKey(
        ContactInfo, on_delete=models.CASCADE, verbose_name=_('Contact info'), related_name='contact_phone')

    class Meta:
        db_table = 'contact_phone'
        verbose_name = _('Contact Phone')
        verbose_name_plural = _('Contact Phone')

    def __str__(self):
        return self.phone_number


class SocialLink(BaseModel):
    link = models.URLField(verbose_name=_('Link'))
    icon = models.ImageField(
        upload_to='social_link/', verbose_name=_('Icon'))
    is_active = models.BooleanField(default=True, verbose_name=_('Is active'))
    contact_info = models.ForeignKey(
        ContactInfo, on_delete=models.CASCADE, verbose_name=_('Contact info'), related_name='social_link')

    class Meta:
        db_table = 'social_link'
        verbose_name = _('Social Link')
        verbose_name_plural = _('Social Link')

    def __str__(self):
        return f"{self.link}"

api/views/core.py
from rest_framework.generics import CreateAPIView
from rest_framework import permissions
from api.serializers.core import TestimonialSerializer
from core.models import Testimonial


class TestimonialAPIView(CreateAPIView):
    serializer_class = TestimonialSerializer
    permission_classes = [permissions.AllowAny]
    model = Testimonial

core/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
from core.models import AboutUs, Testimonial
from blog.models import Blog
from django.db.models import Count
from django.utils.translation import gettext_lazy as _, activate
from service.models import Service, ServiceCategory, ServiceProject

# Create your views here.


class HomeView(View):
    def get(self, request):
        context = {
            'title': _('Home'),
            'services': Service.objects.filter(is_visible=True),
            'blogs': Blog.objects.all(),
            'about_us': AboutUs.objects.filter(is_active=True).last(),
            'services_categories': Service.objects.annotate(Count('projects')).order_by('-projects__count')[:3],
            'services_categories_for_mobile': Service.objects.annotate(Count('projects')).order_by('-projects__count'),
            'projects': ServiceProject.objects.all()[:5],
            'testimonials': Testimonial.objects.filter(is_active=True).order_by('star'),
        }
        return render(request, "home.html", context=context)


class FAQView(TemplateView):
    template_name = 'faq.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('FAQ')
        context['services'] = Service.objects.filter(is_visible=True)
        context['categories'] = self.get_queryset()
        return context

    def get_queryset(self):
        if self.request.GET.get('service'):
            return Service.objects.filter(is_visible=True, slug=self.request.GET.get('service')).first().categories.all()
        return ServiceCategory.objects.all()


class AboutUsView(TemplateView):
    template_name = "about-us.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('About Us')
        context['about_us'] = AboutUs.objects.filter(is_active=True).last()
        return context


class ContactView(TemplateView):
    template_name = "contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Contact')
        return context


def set_language(request):
    if request.GET.get('lang'):
        activate(request.GET.get('lang'))
        response = HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        response.set_cookie('django_language', request.GET['lang'])
        return response

core/templates/partials/footer.html
{% load static i18n %}

<footer class="footer">
    <div class="g-container">
        <div class="footer__wrapper">
            <div class="footer__info">
                <a href="{% url 'core:home'  %}" class="footer__logo">
                    <img src="{% static 'assets/svg/logo.svg' %}" alt="">
                </a>
                <p class="footer__info-text">
                    Trustme Digital is a full-service marketing agency that focuses on driving results via effective
                    and measurable solutions.
                </p>
            </div>
            <div class="footer__links">
                <ul class="footer__list">
                    <p class="footer__title">
                        {% trans 'Əsas keçidlər' %}
                    </p>
                    <li class="footer__item">
                        <a href="{% url 'core:about_us'  %}" class="footer__link">
                            {% trans 'Haqqımızda' %}
                        </a>
                    </li>
                    <li class="footer__item">
                        <a href="{% url 'service:services' %}" class="footer__link">
                            {% trans 'Xidmətlər' %}
                        </a>
                    </li>
                    <li class="footer__item">
                        <a href="{% url 'portfolio:portfolio' %}" class="footer__link">
                            {% trans 'Portfolio' %}
                        </a>
                    </li>
                    <li class="footer__item">
                        <a href="{% url 'blog:blogs' %}" class="footer__link">
                            {% trans 'Bloq' %}
                        </a>
                    </li>
                    <li class="footer__item">
                        <a href="{% url 'career:careers'  %}" class="footer__link">
                            {% trans 'Kariyera' %}
                        </a>
                    </li>
                    <li class="footer__item">
                        <a href="{% url 'core:contact' %}" class="footer__link">
                            {% trans 'Əlaqə' %}
                        </a>
                    </li>

                    <li class="footer__item">
                        <a href="{% url 'core:faq'  %}" class="footer__link">
                            {% trans 'Tez-tez soruşulan suallar' %}
                        </a>
                    </li>
                    <li class="footer__item">
                        <a href="{% url 'website:brief' %}" class="footer__link">
                            {% trans 'Brief göndər' %}
                        </a>
                    </li>
                </ul>
                <ul class="footer__list">
                    <p class="footer__title">
                        {% trans 'Xidmətlərimiz' %}
                    </p>
                    {% for service in services_footer %}
                    <li class="footer__item">
                        <a href="{% url 'service:service-detail' service.slug %}" class="footer__link">
                            {{service.title}}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="footer__contact">
                <p class="footer__title">
                    {% trans 'Əlaqə' %}
                </p>
                <ul class="footer__contact-list">
                    <li class="footer__contact-item">
                        <a href="" class="footer__contact-link">
                            <img src="{% static 'assets/svg/Icons (1).svg' %}" alt=""> {{contact_footer.address}}
                        </a>
                    </li>
                    {% if contact_footer.contact_phone.count > 0 %}
                    {% for phone in contact_footer.contact_phone.all %}
                    <li class="footer__contact-item">
                        <a href="tel:{{phone.phone_number}}" class="footer__contact-link">
                            <img src="{% static 'assets/svg/Icons (2).svg' %}" alt=""> {{phone.phone_number}}
                        </a>
                    </li>
                    {% endfor %}
                    {% endif %}
                    <li class="footer__contact-item">
                        <a href="mailto:{{contact_footer.email}}" class="footer__contact-link">
                            <img src="{% static 'assets/svg/Icons (3).svg' %}" alt=""> {{contact_footer.email}}
                        </a>
                    </li>
                </ul>
                {% if contact_footer.social_link.count > 0 %}
                <ul class="footer__socials-list">
                    {% for social in contact_footer.social_link.all %}
                    <li class="footer__socials-item">
                        <a href="{{social.link}}" class="footer__socaials-link">
                            <img src="{{social.icon.url}}" alt="">
                        </a>
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
        <div class="footer__copyright">
            <p><span>Trustme Digital</span> | Bütün hüquqlar qorunur. 2022</p>
        </div>
    </div>
</footer>

<footer class="mob-footer">
    <div class="g-container">
        <div class="mob-footer___wrapper">
            <a href="" class="mob-footer__logo">
                <img src="{% static 'assets/svg/logo.svg' %}" alt="">
            </a>
            <div class="accordion mob-footer__accordion" id="footerAccordion">
                <div class="accordion-item">
                    <div class="accordion-header" id="footer-headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#footer-collapseOne" aria-expanded="true"
                            aria-controls="footer-collapseOne">
                            {% trans 'Xidmətlərimiz' %}
                            <div class="plusminus"></div>
                        </button>
                    </div>
                    <div id="footer-collapseOne" class="accordion-collapse collapse"
                        aria-labelledby="footer-headingOne">
                        <div class="accordion-body">
                            <ul>
                            {% for service in services_footer %}
                                <li>
                                    <a href="{% url 'service:service-detail' service.slug %}">
                                        {{service.title}}
                                    </a>
                                </li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <div class="accordion-header" id="footer-headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#footer-collapseTwo" aria-expanded="false"
                            aria-controls="footer-collapseTwo">
                            {% trans 'Portfolio' %}
                            <div class="plusminus"></div>
                        </button>
                    </div>
                    <div id="footer-collapseTwo" class="accordion-collapse collapse"
                        aria-labelledby="footer-headingTwo">
                        <div class="accordion-body">
                            <ul>
                                {% for service in services_footer %}
                                <li>
                                    <a href="{% url 'portfolio:portfolio' %}?service={{service.slug}}">
                                        {{service.title}}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <div class="accordion-header" id="footer-headingThree">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#footer-collapseThree" aria-expanded="false"
                            aria-controls="footer-collapseThree">
                            {% trans 'Əlaqə' %}
                            <div class="plusminus"></div>
                        </button>
                    </div>
                    <div id="footer-collapseThree" class="accordion-collapse collapse"
                        aria-labelledby="footer-headingThree">
                        <div class="accordion-body">
                            <ul class="footer__contact-list mb-0">
                                <li class="footer__contact-item">
                                    <a href="" class="footer__contact-link">
                                        <img src="{% static 'assets/svg/Icons (1).svg' %}" alt=""> {{contact_footer.address}}
                                    </a>
                                </li>
                                {% if contact_footer.contact_phone.count > 0 %}
                                {% for phone in contact_footer.contact_phone.all %}
                                <li class="footer__contact-item">
                                    <a href="tel:{{phone.phone_number}}" class="footer__contact-link">
                                        <img src="{% static 'assets/svg/Icons (2).svg' %}" alt=""> {{phone.phone_number}}
                                    </a>
                                </li>
                                {% endfor %}
                                {% endif %}
                                <li class="footer__contact-item">
                                    <a href="mailto:{{contact_footer.email}}" class="footer__contact-link">
                                        <img src="{% static 'assets/svg/Icons (3).svg' %}" alt="">
                                        {{contact_footer.email}}
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <div class="accordion-header" id="footer-headingFour">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#footer-collapseFour" aria-expanded="false"
                            aria-controls="footer-collapseFour">
                            {% trans 'Əsas keçidlər' %}
                            <div class="plusminus"></div>
                        </button>
                    </div>
                    <div id="footer-collapseFour" class="accordion-collapse collapse"
                        aria-labelledby="footer-headingFour">
                        <div class="accordion-body">
                            <ul>
                                <li>
                                    <a href="{% url 'core:about_us'  %}">
                                        {% trans 'Haqqımızda' %}
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'service:services' %}">
                                        {% trans 'Xidmətlər' %}
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'portfolio:portfolio' %}">
                                        {% trans 'Portfolio' %}
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'blog:blogs' %}">
                                        {% trans 'Bloq' %}
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'core:contact' %}">
                                        {% trans 'Əlaqə' %}
                                    </a>
                                </li>

                                <li>
                                    <a href="{% url 'core:faq'  %}">
                                        {% trans 'Tez-tez soruşulan suallar' %}
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'website:brief' %}">
                                        {% trans 'Brief Göndər' %}
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% if contact_footer.social_link.count > 0 %}
            <ul class="mob-footer__socials">
                {% for social in contact_footer.social_link.all %}
                <li>
                    <a href="{{social.link}}">
                        <img src="{{social.icon.url}}" alt="">
                    </a>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <div class="mob-footer__copyright">
                <p><span>Trustme Digital</span> | Bütün hüquqlar qorunur. 2022</p>
            </div>
        </div>
    </div>
</footer>

core/templates/partials/navbar.html
{% load static i18n %}

<header>
    <nav class="navbar navbar--home">
        <div class="g-container">
            <div class="navbar__desktop-wrapper">
                <a href="{% url 'core:home'  %}" class="navbar__logo">
                    <img src="{% static 'assets/svg/trustme_svg 1.svg' %}" alt="">
                </a>

                <ul class="navbar__list">
                    <li class="navbar__item">
                        <a href="{% url 'core:about_us'  %}" class="navbar__link">Haqqımızda</a>
                    </li>
                    <li class="navbar__item">
                        <a href="{% url 'service:services' %}" class="navbar__link">Xidmətlər</a>
                    </li>
                    <li class="navbar__item">
                        <a href="{% url 'portfolio:portfolio' %}" class="navbar__link">Portfolio</a>
                    </li>
                    <li class="navbar__item">
                        <a href="{% url 'blog:blogs' %}" class="navbar__link">Bloq</a>
                    </li>
                    <li class="navbar__item">
                        <a href="{% url 'core:contact'  %}" class="navbar__link">Əlaqə</a>
                    </li>
                </ul>

                <div class="navbar__helper">
                    <a href="{% url 'service:digital-audit' %}" class="g-btn-fill">Rəqəmsal audit</a>

                    <div class="dropdown lang-dropdown">
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                        <button class="dropdown-toggle" type="button" id="selectLanguage" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            <img src="{% static 'assets/svg/global.svg' %}" alt="">
                            <span>
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_language_info for LANGUAGE_CODE as current_lang %}
                                {{ current_lang.code }}
                                <svg width="8" height="6" viewBox="0 0 8 6" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path d="M1 1.5L4 4.5L7 1.5" stroke="" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                </svg>
                            </span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="selectLanguage">
                            <form action="" method="post">{% csrf_token %}
                                {% for language in languages %}
                                {% if language.code != current_lang.code %}
                                <a value="{{ language.code }}" class="dropdown-item" href="{% url 'core:set_language'%}?lang={{language.code}}&next={{request.path}}">{{ language.code }}</a>
                                {% endif %}
                                {% endfor %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="navbar__mobile-wrapper">
                <button class="navbar__open">
                    <img src="{% static 'assets/svg/home-menu-icon.svg' %}" alt="" class="white-item">
                    <img src="{% static 'assets/svg/menu-icon.svg' %}" alt="" class="black-item">
                </button>
                <a href="{% url 'core:home'  %}" class="navbar__mobile-logo">
                    <img src="{% static 'assets/svg/home-mob-menu-logo.svg' %}" alt="" class="white-item">
                    <img src="{% static 'assets/svg/trustme_svg 1.svg' %}" alt="" class="black-item">
                </a>
                <a href="tel:+994702523315" class="navbar__mobile-call">
                    <i class="fa-solid fa-phone-flip"></i>
                </a>
            </div>
        </div>
    </nav>

    <nav class="mob-navbar">
        <div class="g-container h-100">
            <div class="mob-navbar__wrapper">
                <button class="mob-navbar__close">
                    <img src="{% static 'assets/svg/Clear.svg' %}" alt="">
                </button>
                <a href="" class="mob-navbar__logo">
                    <img src="{% static 'assets/svg/trustme_svg 1.svg' %}" alt="">
                </a>
                <ul>
                    <li>
                        <a href="{% url 'core:about_us'  %}">
                            Haqqımızda
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'service:services' %}">
                            Xidmətlər
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'portfolio:portfolio' %}">
                            Portfolio
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'blog:blogs' %}">
                            Bloq
                        </a>
                    </li>
                    <span class="line"></span>
                    <li>
                        <a href="{% url 'career:careers'  %}">
                            Karyera
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'core:contact'  %}">
                            Əlaqə </a>
                    </li>
                    <li>
                        <a href="{% url 'core:faq'  %}">
                            FAQ
                        </a>
                    </li>
                </ul>
                <div class="dropdown mob-lang-dropdown">
                    <button class="dropdown-toggle" type="button" id="selectLanguage" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <span>
                            Azərbaycan dili
                            <svg width="8" height="6" viewBox="0 0 8 6" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path d="M1 1.5L4 4.5L7 1.5" stroke="" stroke-width="1.5" stroke-linecap="round"
                                    stroke-linejoin="round" />
                            </svg>
                        </span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="selectLanguage">

                        <a class="dropdown-item" href="">Rus dili</a>
                        <a class="dropdown-item" href="">İngilis dili</a>
                    </div>
                </div>
            </div>
        </div>
        <img src="{% static 'assets/svg/mob-decor.svg' %}" class="mob-navbar__decor" alt="">
    </nav>
</header>